### PR TITLE
Fix #248

### LINKED ISSUE #248: TypeError: Cannot read property 'queue' of undefined
```
/home/cryptix/scuttle-shell/node_modules/ssb-db/minimal.js:220
    const isEmptyInactiveQueue = !queue.buffer.queue.length && !queue.writing
                                               ^

TypeError: Cannot read property 'queue' of undefined
    at EventEmitter.db.flush (/home/cryptix/scuttle-shell/node_modules/ssb-db/minimal.js:220:48)
    at /home/cryptix/scuttle-shell/node_modules/ssb-db/index.js:129:12
    at /home/cryptix/scuttle-shell/node_modules/pull-stream/sinks/drain.js:20:24
    at /home/cryptix/scuttle-shell/node_modules/pull-stream/throughs/async-map.js:28:19
    at /home/cryptix/scuttle-shell/node_modules/pull-stream/throughs/through.js:19:9
    at PacketStreamSubstream.weird.read (/home/cryptix/scuttle-shell/node_modules/muxrpc/pull-weird.js:33:7)
    at PacketStream._onstream (/home/cryptix/scuttle-shell/node_modules/packet-stream/index.js:200:12)
    at PacketStream.write (/home/cryptix/scuttle-shell/node_modules/packet-stream/index.js:135:41)
    at /home/cryptix/scuttle-shell/node_modules/muxrpc/pull-weird.js:56:15
    at /home/cryptix/scuttle-shell/node_modules/pull-stream/sinks/drain.js:24:37
```

```
scuttle-shell@0.1.3 /home/cryptix/scuttle-shell
└─┬ ssb-server@13.6.0
  └── ssb-db@18.6.4 
```

I changed line 222 to `!queue.buffer && !queue.writing` to have this not crash but I don't know how this is triggered yet.

### PR DESCRIPTION
**Pull request by arj03**
If queue.buffer null this will crash.

### CODE REVIEW

**Comment by jedahan** [comment]
All those negatives were hard for me to grok. How would you feel with:

```js
{
  if (queue.buffer && queue.buffer.queue && queue.buffer.queue.length && queue.writing) return flush.push(cb)
  cb()
}
```

I think they are equivalent, but not positive.

**Comment by jedahan** [comment]
Or
```js
if (queue.writing || (queue.buffer && queue.buffer.queue && queue.buffer.queue.length)) flush.push(cb)
else cb()
```

**Comment by jedahan** [comment]
This was one of those things I missed from coffeescript
```coffeescript
if (queue.writing || queue.buffer?.queue?.length) flush.push(cb)
else cb()
```

**Comment by dominictarr** [comment]
merged into 18.6.5

**Pull request merged**
