### PR TITLE
get ({id: id, meta: true}) to get {key,value,timestamp} format message

### PR DESCRIPTION
**Pull request by dominictarr**
it is kinda annoying that lots of things use a `{key,value,timestamp}` pattern but `sbot.get` doesn't do that.
this tends to mean that sometimes messages don't have received times... this adds a option to keep that.

`meta` is short for metadata. using this name is consistent with other uses for example `links` which uses takes a `meta` option (although that one defaults to true)

Making meta default to true here is probably a breaking change.

### CODE REVIEW

**Comment by christianbundy** [comment]
I dig it. Is this behavior already documented somewhere else, or do we need docs? The tests LGTM, thanks!

**Comment by Happy0** [comment]
Nice, @dominictarr - this is actually something that I ran into in a recent change I made to ssb-chess where I was surprising I couldn't do `msg.key` to get the message ID in a helper function I had passed the message to.

I like that this is implemented in a backward compatible way :)

**Comment by dominictarr** [comment]
@christianbundy now that you mention it... ssb-db's documentation needs a complete overhaul. There is stuff that's completely wrong now, or is left from before scuttlebot even existed I think. get isn't even documented!

**Comment by dominictarr** [comment]
I didn't have the time to do that overhaul, but I wrote documentation for get at least, including this feature.

merged into 19.1.0

**Pull request merged**
