### PR TITLE
Fix intermittent Windows test failures

### PR DESCRIPTION
**Pull request by christianbundy**
Problem: For some reason the Travis CI Windows builds fail
intermittently with a specific error that doesn't make any sense to me.
We've been just restarting the build, since the erorr (can't close the
server because the server is already closed) doesn't matter, but it's
still very obnoxious.

Solution: Ignore the error entirely and don't worry about it. I don't
think that we care if the server is already closed, the important thing
is that it's closed. I'm okay with `close()` being idempotent.

Resolves: #300

### CODE REVIEW

**Comment by christianbundy** [comment]
:(

**Comment by christianbundy** [comment]
FIXED!!!

**Comment by christianbundy** [comment]
(This pulls in changes from #308 because that branch fixed a `Date.now` being used as a filename when it should've been `Date.now()`)

**Comment by mixmix** [comment]
This is a great find, will make maintenance a lot more joyful <3

**Pull request merged**
